### ISSUE TITLE
Bootseed question

### ISSUE THREAD

**Issue by adrianlshaw** [thomas-fossati/draft-psa-token#127]
Looking at the section on **Backwards compatibility considerations**. 

In the new profile, we use some of the EAT claims registered in IANA, such as **_nonce_** and **_eat_profile_**.

I noticed that EAT now has **bootseed**, but we are still using **psa-boot-seed** in this draft. Is there a reason we are not using the EAT one? Are the semantics different? Or is not registered in IANA?

**Comment by hannestschofenig** [comment]
That's a good point, Adrian. The bootseed claim was already introduced in version -07, see https://datatracker.ietf.org/doc/draft-ietf-rats-eat/07/

IMHO we should re-use it. The only difference is that we additionally constrain the size to something between 8 and 32 bytes.

**Comment by thomas-fossati** [comment]
The issue with EAT [`bootseed`](https://www.ietf.org/archive/id/draft-ietf-rats-eat-24.html#section-4.2.13) is that it was not included in the initial IANA assignment lot. As a result, it does not currently have an assigned codepoint that we can utilize.

However, since EAT is now entering the RFC editor queue, it shouldn't be long before IANA assigns the codepoint.
Additionally, we have a normative dependency on EAT, so we must wait for its publication anyway.

All things considered, I agree with Adrian and Hannes that there is a strong argument for reusing it.

**Comment by hannestschofenig** [comment]
Now the bootseed claim is available in the IANA registry

![grafik](https://github.com/thomas-fossati/draft-psa-token/assets/1016643/fc8e62c9-ad4d-41d3-816f-3cf9f4a8e34b)
